<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Incorrect urls: 
https://google.com/language_tools?hl=ru&amp;authuser=0 broken on the page https://google.com/ 13 0
]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="7315" started-at="2015-08-26T13:20:16Z" finished-at="2015-08-26T13:20:23Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7315" started-at="2015-08-26T13:20:16Z" finished-at="2015-08-26T13:20:23Z">
      <class name="TestCheckLinks">
        <test-method status="FAIL" signature="testCheck()[pri:0, instance:TestCheckLinks@16df1832]" name="testCheck" duration-ms="7295" started-at="2015-08-26T17:20:16Z" description="Test to check src and href in project" finished-at="2015-08-26T17:20:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail test
Incorrect urls: 
https://google.com/language_tools?hl=ru&amp;authuser=0 broken on the page https://google.com/ 13 0
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail test
Incorrect urls: 
https://google.com/language_tools?hl=ru&amp;authuser=0 broken on the page https://google.com/ 13 0

	at org.testng.Assert.fail(Assert.java:94)
	at TestCheckLinks.testCheck(TestCheckLinks.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCheck -->
      </class> <!-- TestCheckLinks -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
